RecipeWeekly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('main.urls')),

    url(r'^oauth/', include('social_django.urls', namespace='social')),

    # url(r'^', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns 
#     # urlpatterns += patterns('', 

    #     (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
    # )

main/urls.py
from django.conf.urls import url, include 
from django.contrib.auth import views as auth_views

from .views import recipes, users, api 


urlpatterns = [
	url(r'^$', recipes.home, name='home'),
	url(r'^about/$', recipes.about, name='about'),
	url(r'^recipes/$', recipes.RecipeList.as_view(), name='recipe_list'),
	url(r'^recipes/(?P<pk>[0-9]+)$', recipes.RecipeDetail.as_view(), name='recipe_detail'),
	url(r'^ingredients/$', recipes.IngredientList.as_view(), name='ingredient_list'),
	url(r'^ingredients/(?P<pk>[0-9]+)$', recipes.IngredientDetail.as_view(), name='ingredient_detail'),
	url(r'^create/$', recipes.RecipeCreate.as_view(), name='create_recipe'),
	# url(r'^create/$', recipes.create_recipe, name='create_recipe'),

	url(r'^search/$', recipes.Search.as_view(), name='search'),


	# Users
	url(r'^users/$', users.UserList.as_view(), name='user_list'),
	url(r'^users/(?P<slug>\w+)$', users.UserDetail.as_view(), name='user_detail'),
	url(r'^register/$', users.UserRegistrationView.as_view(), name='user_registration'),
	url(r'^login/$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', users.logout_user, name='logout'),
	url(r'^delete_user/$', users.delete_user, name='delete_user'),

	url(r'^profile/$', users.update_profile, name='update_profile'),
	url(r'^profile/password/$', users.change_password, name='change_password'),

	url(r'^save_recipe/$', users.add_to_user_saved_recipes, name='save_recipe'),


	# API urls
	url(r'^api/$', api.Root.as_view()),
	url(r'^api/recipes/$', api.RecipeList.as_view()),
	# url(r'^api/recipes/create/$', api.RecipeCreate.as_view()),
	url(r'^api/recipes/save/$', api.SaveRecipe.as_view()),
	url(r'^api/recipes/like/$', api.LikeRecipe.as_view()),
	url(r'^api/recipes/dislike/$', api.DislikeRecipe.as_view()),
	url(r'^api/recipes/(?P<pk>[0-9]+)$', api.RecipeDetail.as_view()),
	url(r'^api/users/$', api.UserList.as_view(), name='api_users_list'),
	url(r'^api/users/(?P<pk>[0-9]+)$', api.UserDetail.as_view()),

	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

# url(r'^(?P<recipe_id>[0-9]+)/$', views.detail, name='detail'), 
# access captured group () in view method through self.args[0] or self.kwargs

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver 
from django.utils import timezone 


import logging
logger = logging.getLogger('main')


class Ingredient(models.Model):
	raw_name 	= models.CharField(max_length=200) # Lowercase and hyphens in between words
	name 		= models.CharField(max_length=200) # Capitalized and with spaces

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.name = self.raw_name.replace('-', ' ').title()
		return super(Ingredient, self).save(*args, **kwargs)


# Encompasses recipes from external API source, as well as user uploaded
class Recipe(models.Model):
	name	 		= models.CharField(max_length=300) 
	creator 		= models.ForeignKey('Profile', related_name='created_recipes', null=True, blank=True)
	is_yummly_recipe = models.BooleanField(default=False)
	is_user_recipe	= models.BooleanField(default=False)
	ingredient_list	= models.TextField() # String representation
	ingredients 	= models.ManyToManyField(Ingredient) # Foreign key model representation
	instructions	= models.TextField()
	photo			= models.ImageField(upload_to='recipe_photos/', null=True, blank=True)

	# Machine learning algorithm to determine similar recipes
	related_recipes	= models.ManyToManyField('self', blank=True)

	# Data included in Yummly API
	yummly_url	 	= models.CharField(max_length=300, blank=True) 
	yummly_source 	= models.CharField(max_length=300, blank=True) 
	yummly_rating	= models.IntegerField(default=0, blank=True)
	yummly_time_in_seconds	= models.IntegerField(default=0, blank=True) 
	yummly_image_url = models.CharField(max_length=300, blank=True)

	# Taste profile from Yummly
	bitter			= models.FloatField(blank=True, default=0)
	meaty			= models.FloatField(blank=True, default=0)
	salty			= models.FloatField(blank=True, default=0)
	sour			= models.FloatField(blank=True, default=0)
	sweet			= models.FloatField(blank=True, default=0)
	piquant			= models.FloatField(blank=True, default=0)

	# Timestamps
	date_created	= models.DateTimeField(editable=False)
	date_modified	= models.DateTimeField(editable=False)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.__update_timestamps()
		return super(Recipe, self).save(*args, **kwargs)

	def __update_timestamps(self):
		if not self.id: # Being created
			self.date_created = timezone.now()
		self.date_modified = timezone.now()

	def _post_save_link_ingredients(self):
		for ingredient_name in self.ingredient_list.split(' '):
			try:
				ingredient = Ingredient.objects.get(raw_name=ingredient_name)
			except Ingredient.DoesNotExist:
				ingredient = Ingredient.objects.create(raw_name=ingredient_name)

			if ingredient not in self.ingredients.all():
				self.ingredients.add(ingredient)

	def num_saves(self):
		count = self.profiles_saved.all().count()
		return count

@receiver(post_save, sender=Recipe)
def recipe_saved(sender, instance, created, **kwargs):
	instance._post_save_link_ingredients()


# Each user has a profile with additional information
class Profile(models.Model):
	user 			= models.OneToOneField(User, on_delete=models.CASCADE)
	bio 			= models.TextField(max_length=500, blank=True)
	saved_recipes 	= models.ManyToManyField(Recipe, related_name='profiles_saved', blank=True)
	
	# voted_recipes	= models.ManyToManyField(Recipe, through='RecipeVote', related_name='profiles_voted')
	liked_recipes	= models.ManyToManyField(Recipe, related_name='profiles_liked', blank=True)
	disliked_recipes = models.ManyToManyField(Recipe, related_name='profiles_disliked', blank=True)

	date_created 	= models.DateTimeField(auto_now_add=True) 
	date_modified 	= models.DateTimeField(auto_now=True) 


	def __str__(self):
		return self.user.username + "'s profile"


	# def liked_recipes(self):
	# 	liked_recipes = self.voted_recipes.filter(recipevote__liked=True)
	# 	return liked_recipes

	# def disliked_recipes(self):
	# 	disliked_recipes = self.voted_recipes.filter(recipevote__liked=False)
	# 	return disliked_recipes



# Listeners to keep user profile in sync with its corresponding user
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	profile = instance.profile 
	# profile.liked_recipes = profile.voted_recipes.filter(recipevote__liked=True)
	# profile.disliked_recipes = profile.voted_recipes.filter(recipevote__liked=False)
	profile.save() 



# Keeps track of like and dislike of a user for a recipe
class RecipeVote(models.Model):
	user_profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	recipe 		= models.ForeignKey(Recipe, on_delete=models.CASCADE)

	liked 		= models.NullBooleanField(default=None)
	# disliked	= models.NullBooleanField()

	date_modified = models.DateTimeField(auto_now=True)


	def __str__(self):
		if self.liked == True: 		s = " likes "
		elif self.liked == False: 	s = " dislikes "
		else: 						s = " neutral to "

		return str(self.user_profile) + s + str(self.recipe)

main/views.py
import pprint
import logging
logger = logging.getLogger('main')
import json
from urllib.request import Request as url_request
import facebook # Facebook API sdk

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, View
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, AdminPasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.backends import ModelBackend
from django.contrib import messages 
from django.conf import settings
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from social_django.models import UserSocialAuth
from rest_framework.views import APIView
from rest_framework.response import Response 
from rest_framework import status 
from rest_framework import generics
from rest_framework import permissions 
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse as api_reverse

from .models import Recipe, Ingredient
from .forms import UserForm, UserRegistrationForm, UserInfoForm, ProfileInfoForm
from .serializers import RecipeSerializer, RecipeDetailSerializer, UserSerializer, UserDetailSerializer, RecipeCreateSerializer


def home(request):
	context = {}
	return render(request, 'main/home.html', context)


############################################################
# API Views
############################################################

@api_view(['GET'])
def api_root(request, format=None):
	return Response({
		'users': api_reverse('api_users_list', request=request, format=format),
	})

class APIRecipeList(generics.ListAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeSerializer

class APIRecipeCreate(generics.CreateAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeCreateSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

	def perform_create(self, serializer):
		serializer.save(creator=self.request.user, is_user_recipe=True)

class APIRecipeDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Recipe.objects.all()
	serializer_class = RecipeDetailSerializer 

class APIUserList(generics.ListAPIView):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class APIUserDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = User.objects.all()
	serializer_class = UserDetailSerializer 

############################################################
# Recipes
############################################################

class RecipeList(ListView):
	model = Recipe
	template_name = 'main/recipe_list.html'

	#queryset = Recipe.objects.order_by('name')

	# Recipe models to pass to template
	def get_queryset(self):
		return Recipe.objects.order_by('name')[:20]


	# Other values to pass to template
	def get_context_data(self, **kwargs):
		context = super(RecipeList, self).get_context_data(**kwargs)

		context['liked_recipes'] = self.request.user.profile.liked_recipes()
		context['disliked_recipes'] = self.request.user.profile.disliked_recipes()
		context['total_recipe_count'] = Recipe.objects.count()
		return context


class RecipeDetail(DetailView):
	model = Recipe
	template_name = 'main/recipe_detail.html'

	context_object_name = 'recipe'


# class UserRecipeCreate(CreateView):
# 	model = UserRecipe 
# 	template_name = 'main/user_recipe_create.html'
# 	fields = ('name', 'ingredients', 'instructions',)

@login_required
def create_recipe(request):
	context = {}

	return render(request, 'main/user_recipe_create.html', context)

############################################################
# Ingredients
############################################################

class IngredientList(ListView):
	model = Ingredient
	template_name = 'main/ingredient_list.html'

	def get_queryset(self):
		return Ingredient.objects.order_by('name')

class IngredientDetail(DetailView):
	model = Ingredient
	template_name = 'main/ingredient_detail.html'

	# context_object_name = 'ingredient'



############################################################
# Users
############################################################

class UserList(ListView):
	model = User
	template_name = 'main/user_list.html'

	def get_queryset(self):
		return User.objects.all()

class UserDetail(DetailView):
	model = User
	template_name = 'main/user_detail.html'
	slug_field = 'username' # slug is in url, ex: users/<username>
	context_object_name = 'viewed_user'

	# def get_queryset(self):
	# 	return User.objects.filter(username=)

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get context
		context = super(UserDetail, self).get_context_data(**kwargs)

		user = context['viewed_user']
		try: 
			facebook_login = user.social_auth.get(provider='facebook')
			context['facebook_login'] = facebook_login

			oauth_token = facebook_login.extra_data['access_token']
			graph = facebook.GraphAPI(access_token=oauth_token)

			profile = graph.get_object("me")
			picture = graph.get_connections("me", "picture")

			context['profile_picture_url'] = picture['url']


		except UserSocialAuth.DoesNotExist:
			facebook_login = None
		
		return context



class UserRegistrationView(FormView):
	form_class = UserRegistrationForm
	template_name = 'users/register.html'
	success_url = '/' # reverse('main:home')

	def form_valid(self, form):
		form.save()
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password1')

		user = authenticate(username=username, password=password)
		if user is not None: 
			login(self.request, user)
			messages.info(self.request, "Logged into new account for {}.".format(username))
		else:
			messages.error(self.request, "Created account, but failed to login {}.".format(username))

		return super(UserRegistrationView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(UserRegistrationView, self).get_context_data(**kwargs)
		return context


# def login_user(request):
# 	return render(request, 'users/login.html')

def logout_user(request):
	logout(request)
	return redirect('/')

@login_required
def delete_user(request):
	user = request.user
	try:
		user.delete()
		messages.info(request, "Successfully deleted user {}.".format(user.username))
	except Exception as e:
		messages.error(request, "Failed to delete user {}.".format(user.username))

	return redirect('home')


# Page for a user to view and update their profile
@login_required
def update_profile(request):
	user = request.user
	template_name = 'users/update_profile.html'
	context = {}

	if request.method == 'POST':
		# Process submitted form
		user_form = UserInfoForm(request.POST, instance=user)
		profile_form = ProfileInfoForm(request.POST, instance=user.profile)
		context['user_form'] = user_form
		context['profile_form'] = profile_form

		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Profile updated.')
			return redirect('update_profile')
		else:
			messages.error(request, 'Please correct the errors below.')

	else: 
		# Display form with existing info 
		user_form = UserInfoForm(instance=user)
		profile_form = ProfileInfoForm(instance=user.profile)
		context['user_form'] = user_form
		context['profile_form'] = profile_form

		try: 
			facebook_login = user.social_auth.get(provider='facebook')

			oauth_token = facebook_login.extra_data['access_token']
			graph = facebook.GraphAPI(access_token=oauth_token)
			profile = graph.get_object("me")

			picture = graph.get_connections("me", "picture")
			context['profile_picture_url'] = picture['url']


		except UserSocialAuth.DoesNotExist:
			facebook_login = None

		can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())
		context['facebook_login'] = facebook_login
		context['can_disconnect'] = can_disconnect

	return render(request, template_name, context)



# AJAX request to add to a user's saved recipes
@login_required
def add_to_user_saved_recipes(request):
	response_data = {}
	if request.method == 'POST':
		recipe_id = request.POST.get('recipe_id')
		try:
			recipe = Recipe.objects.get(id=recipe_id)
		except Recipe.DoesNotExist:
			recipe = None

		user_profile = request.user.profile

		# Like the recipe. If it is already liked, unlike it. 
		if user_profile.saved_recipes.filter(pk=recipe.pk).exists():
			user_profile.saved_recipes.remove(recipe)
			response_data['message'] = 'Removed recipe %s from %s\'s saved recipes' % (recipe_id, request.user.username)
		else:
			user_profile.saved_recipes.add(recipe)
			response_data['message'] = 'Added recipe %s to %s\'s saved recipes' % (recipe_id, request.user.username)

	else:
		response_data['message'] = 'Submission type needs to be POST.'
	
	return JsonResponse(response_data)




@login_required
def change_password(request):
	if request.user.has_usable_password():
		PasswordForm = PasswordChangeForm
	else:
		PasswordForm = AdminPasswordChangeForm

	if request.method == 'POST':
		form = PasswordForm(request.user, request.POST)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, 'Your password was successfully updated.')
			return redirect('home')
		else:
			messages.error(request, 'Please correct the errors below.')
	else:
		form = PasswordForm(request.user)

	return render(request, 'users/change_password.html', {'form': form } )

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}

<div class="container">    
  <h1>About</h1>

  <div class="row about-cards">

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Browser Makes Request</h3>
        </div>
        <div class="panel-body">
          The user enters a url address into their browser, such as <code>https://recipy.com/recipes/</code>.
          Browser -> Internet Provider -> Hosting Server
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Server Receives Request</h3>
        </div>
        <div class="panel-body">
          The files for the website all exist on the server, and sends back the file specified by the request. 
          In this case, our server is running the Django Python web framework. 
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">URL Mapping</h3>
        </div>
        <div class="panel-body">
          The first thing Django does is look at the url and map it to a view, which handles the request logic. 
          <code>url(r'^recipes/$', recipes.RecipeList.as_view(), name='recipe_list')</code>

        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">View</h3>
        </div>
        <div class="panel-body">
          This view does three things: link it with the Recipe model, determine the html template to be rendered, and return a set of recipes.
          <pre>
class RecipeList(ListView):
  model = Recipe
  template_name = 'main/recipe_list.html'

  # Recipe models to pass to template
  def get_queryset(self):
    return Recipe.objects.order_by('name')[:20]
          </pre>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Model</h3>
        </div>
        <div class="panel-body">
          The Recipe model is a Python class that simplifies storage in a SQL database. 
          <pre>
class Recipe(models.Model):
  name      = models.CharField(max_length=200) 
          </pre>

          It also can correspond directly to other models in the database.
          <pre>
  ingredients   = models.ManyToManyField(Ingredient) 
          </pre>

        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Template</h3>
        </div>
        <div class="panel-body">
          This is where the HTML is created that can be sent to the browser and interacted with. 
        </div>
      </div>
    </div>


  </div>
</div>

{% endblock content %}

main/templates/main/ingredient_detail.html
{% extends "main/base.html" %}

{% block content %}

	<div class="container">

		<h1>{{ ingredient.name }}</h1>

		<p>Recipes:
			<ul>
			{% for recipe in ingredient.recipe_set.all %}
				<li><a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a></li>
			{% endfor %}
			</ul>
		</p>
	</div>

{% endblock content %}

main/templates/main/ingredient_list.html
{% extends "main/base.html" %}

{% block content %}

	<div class="container">

		<h1>Ingredients <span class="text-muted">({{ ingredient_list.count }} total)</span></h1>
		{% if ingredient_list %}
			<ul class="list-group">
			{% for ingredient in ingredient_list %}
				<li class="list-group-item">
          <i class="fa fa-apple" aria-hidden="true"></i>
					<a href="{% url 'ingredient_detail' ingredient.id %}">{{ ingredient.name }}</a>
					({{ ingredient.recipe_set.count }} recipes)
				</li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No ingredients listed.</p>
		{% endif %}

	</div>

{% endblock content %}

main/templates/main/recipe_list.html
{% extends "main/base.html" %}
{% load myfilters %}


{% block content %}

<div class="container">

  <h1>Recently Added User Recipes</h1>
  <div class="row">
    {% for recipe in recent_user_recipes %}
      <div class="col-md-3 col-sm-4">
        {% include "components/recipe_card.html" %}
      </div>
    {% endfor %}
  </div>

  <hr>

  <h1>Most Starred Yummly Recipes</h1>
  <div class="row">
    {% for recipe in most_saved_yummly_recipes %}
      <div class="col-md-3 col-sm-4">
        {% include "components/recipe_card.html" %}
      </div>
    {% endfor %}
  </div>

</div>

{% endblock content %}

main/templates/main/user_list.html
{% extends "main/base.html" %}


{% block content %}

  <script> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>

  <div class="container">

    <h1>Users</h1>

    <div class="row">
      {% if user_list %}
      <ul class="list-group favorites-list">

        {% for user in user_list %}
        <li class="list-group-item">
          <i class="fa fa-spoon" aria-hidden="true"></i>
          <a href="{% url 'user_detail' user.username %}">{{ user.username }}</a>
        </li>
        {% endfor %}

      </ul>
      {% else %}
      <p>No users.</p>
      {% endif %}
    </div>


  </div>

{% endblock content %}

main/templates/main/user_recipe_create.html
{% extends 'main/base.html' %}
{% load myfilters %}


{% block content %}
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h1 class="panel-title">Create New Recipe</h1>
        </div>
        <div class="panel-body">

          <form id="create-recipe-form" class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <!-- Recipe Name -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_name">Recipe Name</label>
              <div class="col-md-4">
                <input name="name" id="id_name" type="text" class="form-control" required autofocus>
              </div> 
              {% if form.name.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.name.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>

            <!-- Ingredients -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_currentIngredient">Ingredients</label>
              <div class="col-md-3 col-xs-9">
                <input name="currentIngredient" type="text" id="id_currentIngredient" class="form-control">
                <input name="ingredient_list" type="text" id="id_ingredient_list" class="form-control hidden">
              </div> 
              <div class="col-md-1 col-xs-3">
                <button id="addIngredientsButton" type="button" class="btn btn-info" tabindex="-1">Add</button>
              </div>
              {% if form.ingredient_list.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.ingredient_list.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>
            <div class="form-group">
              <div class="col-md-offset-2 col-md-3 col-xs-9">
                <ul id="ingredient-list-group" class="list-group"></ul>
              </div>
            </div>

            <!-- Instructions -->
            <div class="form-group">
              <label class="control-label col-md-2" for="id_instructions">Instructions</label>
              <div class="col-md-8">
                <textarea name="instructions" id="id_instructions" type="textarea" class="form-control" rows="6" placeholder="Explain how to make your recipe." form="create-recipe-form" required></textarea>
              </div> 
              {% if form.instructions.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.instructions.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>

            <!-- Picture -->
            <div class="form-group">
              <label class="control-label col-md-2">Photo</label>
              <div class="col-md-4">
                <!--<label class="btn btn-info btn-file" for="id_photo">
                  Upload Photo <input name="photo" type="file" id="id_photo" style="display: none;" required>
                </label>-->
                <div class="fileinput fileinput-new" data-provides="fileinput">
                  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                  <div>
                    <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
                      <input name="photo" type="file" id="id_photo" required>
                    </span>
                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                  </div>
                </div>                
              </div> 
              {% if form.photo.errors %}
                <div class="col-md-4 errors">
                  <p class="text-danger">{% for error in form.photo.errors %}{{ error }} {% endfor %}</p>
                </div>
              {% endif %}
            </div>



            <!-- Submit button -->
            <div class="form-group">
              <div class="col-md-offset-2 col-md-4">
                <button type="submit" class="btn btn-primary btn-block">Create</button>
              </div>
            </div>

          </form>

          {# {{ form.as_p }} #}


      </div>
    </div>
  </div>

</div>
{% endblock %}

main/templates/main/yummlyrecipe_list.html
{% extends "main/base.html" %}


{% block content %}
{% with liked_recipes=user.profile.liked_recipes.all %}

  <script> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>

	<div class="container">

		<h1>Recipes <span class="text-muted">({{ yummlyrecipe_list.count }} out of {{ total_recipe_count }} total)</span></h1>

    <div class="row">
  	  {% if yummlyrecipe_list %}
  		<ul class="list-group favorites-list">

  		  {% for recipe in yummlyrecipe_list %}
  			<li class="list-group-item">

          {% if recipe in liked_recipes and user.is_authenticated %}
          <i class="fa fa-star" data-recipe-id="{{ recipe.id }}" aria-hidden="true"></i>
          {% elif user.is_authenticated %}
          <i class="fa fa-star-o" data-recipe-id="{{ recipe.id }}" aria-hidden="true"></i>
          {% else %}
          <a class="nostyle" href="{% url 'login' %}?next={% url 'recipe_list' %}"><i class="fa fa-star-o needs-login"></i></a>
          {% endif %}

          <a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.name }}</a>
          <span class="badge"><span class="favorite_count">{{ recipe.profile_set.count }}</span> stars</span>
  			</li>
  		  {% endfor %}

  		</ul>
  	  {% else %}
  		<p>No recipes listed.</p>
  	  {% endif %}
    </div>


	</div>

{% endwith %}
{% endblock content %}